import { Stethoscope, Calendar, Users, Clock, Plus, CheckCircle, XCircle } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export default function ClinicPage() {
  const doctors = [
    {
      id: "doc-1",
      name: "Dr. Dipankar Sarma",
      specialty: "General Medicine / Physician",
      opdDays: "Mon, Wed, Fri (09:00 AM - 01:00 PM)",
      maxPatients: 25,
      activeToday: true,
    },
    {
      id: "doc-2",
      name: "Dr. Ananya Baruah",
      specialty: "Cardiology",
      opdDays: "Tue, Thu, Sat (10:00 AM - 02:00 PM)",
      maxPatients: 20,
      activeToday: true,
    },
  ];

  const todayTokens = [
    {
      token: "#1",
      patient: "Pranjal Deka",
      time: "10:00 AM",
      doctor: "Dr. Dipankar Sarma",
      complaint: "Fever and mild headache for 2 days",
      status: "completed",
    },
    {
      token: "#2",
      patient: "Geeta Kalita",
      time: "10:15 AM",
      doctor: "Dr. Dipankar Sarma",
      complaint: "Follow-up BP consultation",
      status: "completed",
    },
    {
      token: "#3",
      patient: "Manash Borah",
      time: "10:30 AM",
      doctor: "Dr. Dipankar Sarma",
      complaint: "Chest tightness during exercise",
      status: "waiting",
    },
    {
      token: "#4",
      patient: "Bikram Saikia",
      time: "10:45 AM",
      doctor: "Dr. Dipankar Sarma",
      complaint: "Seasonal cough and throat pain",
      status: "waiting",
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground">
            Clinic & OPD Management
          </h1>
          <p className="text-sm text-muted-foreground">
            Doctors roster, schedule slots, and live patient queue generated by voice bookings.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <Button size="sm">
            <Plus className="mr-1.5 h-4 w-4" />
            <span>Add Doctor</span>
          </Button>
        </div>
      </div>

      {/* OPD Summary KPIs */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Total Booked (Today)</p>
              <div className="text-2xl font-bold mt-1">42</div>
            </div>
            <div className="p-2.5 rounded-lg bg-primary/10 text-primary">
              <Calendar className="h-5 w-5" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Waiting in OPD</p>
              <div className="text-2xl font-bold mt-1">16</div>
            </div>
            <div className="p-2.5 rounded-lg bg-amber-500/10 text-amber-500">
              <Clock className="h-5 w-5" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Consultation Done</p>
              <div className="text-2xl font-bold mt-1">24</div>
            </div>
            <div className="p-2.5 rounded-lg bg-emerald-500/10 text-emerald-500">
              <CheckCircle className="h-5 w-5" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">No-Shows</p>
              <div className="text-2xl font-bold mt-1">2</div>
            </div>
            <div className="p-2.5 rounded-lg bg-red-500/10 text-red-500">
              <XCircle className="h-5 w-5" />
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Live Token Queue Table */}
        <div className="lg:col-span-2">
          <Card>
            <CardHeader className="pb-3 border-b">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-base font-semibold">Today&apos;s Live OPD Queue</CardTitle>
                  <CardDescription className="text-xs">
                    Live ordered tokens booked through phone AI calls
                  </CardDescription>
                </div>
                <Badge variant="outline">Today, Oct 1</Badge>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className="border-b bg-muted/40 text-muted-foreground">
                    <tr>
                      <th className="p-3.5 font-medium">Token</th>
                      <th className="p-3.5 font-medium">Patient Name</th>
                      <th className="p-3.5 font-medium">Slot Time</th>
                      <th className="p-3.5 font-medium">Doctor</th>
                      <th className="p-3.5 font-medium">Reported Complaint</th>
                      <th className="p-3.5 font-medium text-right">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {todayTokens.map((item) => (
                      <tr key={item.token} className="hover:bg-muted/30 transition-colors">
                        <td className="p-3.5 font-bold text-foreground">
                          <span className="inline-block rounded bg-primary/10 px-2 py-0.5 text-primary">
                            {item.token}
                          </span>
                        </td>
                        <td className="p-3.5 font-medium text-foreground">{item.patient}</td>
                        <td className="p-3.5 text-muted-foreground">{item.time}</td>
                        <td className="p-3.5 text-foreground">{item.doctor}</td>
                        <td className="p-3.5 text-muted-foreground">{item.complaint}</td>
                        <td className="p-3.5 text-right">
                          <Badge
                            variant={item.status === "completed" ? "success" : "secondary"}
                            className="text-[10px]"
                          >
                            {item.status === "completed" ? "Completed" : "Waiting"}
                          </Badge>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Doctors Roster */}
        <div className="space-y-4">
          <Card>
            <CardHeader className="pb-3 border-b">
              <CardTitle className="text-base font-semibold">Doctors on Duty</CardTitle>
              <CardDescription className="text-xs">
                Active clinical consultants available for AI booking
              </CardDescription>
            </CardHeader>
            <CardContent className="p-4 space-y-4">
              {doctors.map((doc) => (
                <div key={doc.id} className="rounded-lg border p-3.5 space-y-2 bg-muted/20">
                  <div className="flex items-start justify-between">
                    <div className="flex items-center space-x-2">
                      <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-primary">
                        <Stethoscope className="h-4 w-4" />
                      </div>
                      <div>
                        <div className="text-xs font-semibold text-foreground">{doc.name}</div>
                        <div className="text-[11px] text-muted-foreground">{doc.specialty}</div>
                      </div>
                    </div>
                    <Badge variant="success" className="text-[10px]">
                      Available
                    </Badge>
                  </div>
                  <div className="border-t pt-2 text-[11px] text-muted-foreground flex justify-between">
                    <span>Schedule</span>
                    <span className="text-foreground font-medium">{doc.opdDays}</span>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
